# Generated by Django 6.0.5 on 2026-06-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', '⏳ Pending Review'), ('Approved', '✅ Approved / Confirmed')], default='Pending', max_length=20),
        ),
    ]
