# Generated by Django 6.0.5 on 2026-06-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='proposed_date',
            field=models.DateField(blank=True, help_text='Propose a new date to the patient.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='proposed_time',
            field=models.CharField(blank=True, choices=[('09:00 AM', '09:00 AM - 10:00 AM'), ('10:00 AM', '10:00 AM - 11:00 AM'), ('11:00 AM', '11:00 AM - 12:00 PM'), ('02:00 PM', '02:00 PM - 03:00 PM'), ('03:00 PM', '03:00 PM - 04:00 PM')], help_text='Propose a new time to the patient.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', '⏳ Pending Review'), ('Approved', '✅ Approved / Confirmed'), ('Rescheduled', '🔄 Rescheduled by Admin (Awaiting Patient Approval)'), ('Rejected_By_Patient', '❌ Reschedule Rejected by Patient')], default='Pending', max_length=20),
        ),
    ]
