# Generated by Django 6.0.5 on 2026-06-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_booking_proposed_date_booking_proposed_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved / Confirmed'), ('Rescheduled', 'Rescheduled by Admin (Awaiting Patient Approval)'), ('Rejected_By_Patient', 'Reschedule Rejected by Patient')], default='Pending', max_length=20),
        ),
    ]
