# Generated by Django 6.0.5 on 2026-06-04 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactmessage_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='proposed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='proposed_time',
            field=models.CharField(blank=True, choices=[('09:00 AM', '09:00 AM - 10:00 AM'), ('10:00 AM', '10:00 AM - 11:00 AM'), ('11:00 AM', '11:00 AM - 12:00 PM'), ('02:00 PM', '02:00 PM - 03:00 PM'), ('03:00 PM', '03:00 PM - 04:00 PM')], max_length=20, null=True),
        ),
    ]
