# Generated by Django 6.0.5 on 2026-06-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='proposed_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='proposed_time',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rescheduled', 'Rescheduled'), ('Rejected_By_Patient', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
