# Generated by Django 6.0.5 on 2026-06-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_booking_proposed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='proposed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='proposed_time',
            field=models.CharField(blank=True, choices=[('09:00 AM', '09:00 AM - 10:00 AM'), ('10:00 AM', '10:00 AM - 11:00 AM'), ('11:00 AM', '11:00 AM - 12:00 PM'), ('02:00 PM', '02:00 PM - 03:00 PM'), ('03:00 PM', '03:00 PM - 04:00 PM')], max_length=20, null=True),
        ),
    ]
