# Generated by Django 6.0.5 on 2026-06-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_userprofile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
    ]
